"""Slice 02 measurement gates. Writes docs/budget.md.

Run once the NIM key is authorized:  python scripts/probe_budget.py

Measures rather than assumes:
  1. auth actually works for inference (listing models does not prove this --
     the /models endpoint is public and answers a garbage key)
  2. reasoning-OFF produces parseable JSON
  3. the real context ceiling of the answering model
  4. observed throughput against the documented ~40 RPM
"""

import json
import os
import pathlib
import sys
import time

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from hydramem import llm  # noqa: E402

REPORT = pathlib.Path("docs/budget.md")
PROBE_SIZES = [8_000, 60_000, 120_000, 140_000, 200_000, 300_000, 500_000, 1_000_000]


def check_auth(model):
    try:
        llm.complete([{"role": "user", "content": "Reply with the single word: ok"}],
                     model=model, max_tokens=8, retries=1)
        return True, "ok"
    except Exception as exc:  # noqa: BLE001
        return False, str(exc)[:200]


def check_json(model):
    """Reasoning OFF must yield strictly parseable JSON, no thinking tokens."""
    messages = [{
        "role": "user",
        "content": 'Extract facts as JSON only, no prose:\n'
                   '"I moved from Acme to Globex in March 2024."\n'
                   'Schema: {"facts":[{"subject":str,"predicate":str,"value":str}]}',
    }]
    try:
        text = llm.complete(messages, model=model, reasoning=False,
                            max_tokens=512, retries=2)["text"]
        json.loads(text.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip())
        return True, "parsed"
    except Exception as exc:  # noqa: BLE001
        return False, str(exc)[:200]


# Latency is only real on an uncached call. Persisted here so a rerun that hits
# the cache reports the measurement instead of overwriting it with 0.0s -- the
# cost table in slice 14 depends on these being genuine wall-clock numbers.
LATENCY_FILE = pathlib.Path("docs/ceiling-latency.json")


def find_ceiling(model):
    """Send progressively larger real requests until the endpoint refuses."""
    measured = json.loads(LATENCY_FILE.read_text()) if LATENCY_FILE.exists() else {}
    results = []
    # ~1 token per word for this filler; close enough to walk the boundary.
    for target in PROBE_SIZES:
        filler = ("the quick brown fox jumps over the lazy dog " * (target // 9))
        prompt = f"Count nothing. Reply 'ok'.\n\n{filler}"
        actual = llm.count_tokens(prompt)
        try:
            start = time.time()
            out = llm.complete([{"role": "user", "content": prompt}], model=model,
                               max_tokens=16, retries=1)
            if out["cached"]:
                secs = measured.get(str(actual))
                note = "cached" if secs is None else f"{secs}s (earlier run)"
            else:
                secs = round(time.time() - start, 1)
                measured[str(actual)] = secs
                note = f"{secs}s"
            results.append((actual, True, out["usage"]["prompt_tokens"], secs))
            print(f"  {actual:>9,} tokens  OK   {note}")
        except Exception as exc:  # noqa: BLE001
            results.append((actual, False, 0, None))
            print(f"  {actual:>9,} tokens  FAIL {str(exc)[:110]}")
            break

    LATENCY_FILE.parent.mkdir(parents=True, exist_ok=True)
    LATENCY_FILE.write_text(json.dumps(measured, indent=2, sort_keys=True))
    return results


def measure_rpm(model, n=8):
    """Throughput against the live endpoint.

    Every call carries a nonce so it cannot hit the disk cache. Without this the
    probe measures local disk speed and reports a five-figure RPM -- a
    confidently wrong number, which is exactly what this file exists to avoid.
    """
    nonce = os.urandom(8).hex()
    start = time.time()
    ok = 0
    for i in range(n):
        try:
            llm.complete(
                [{"role": "user", "content": f"Reply with the number {i}. [{nonce}]"}],
                model=model, max_tokens=8, retries=1, temperature=0.0,
            )
            ok += 1
        except Exception:  # noqa: BLE001
            pass
    elapsed = time.time() - start
    return ok, round(elapsed, 1), round(ok / elapsed * 60, 1) if elapsed else 0.0


def main():
    lines = ["# Budget and measured limits", "",
             "Generated by `scripts/probe_budget.py`. Every number here is measured,",
             "not taken from a spec sheet.", ""]

    print("auth check...")
    for label, model in [("extraction", llm.EXTRACT_MODEL),
                         ("answering", llm.ANSWER_MODEL),
                         ("answering fallback", llm.ANSWER_FALLBACK)]:
        ok, detail = check_auth(model)
        print(f"  {label:<20} {model:<40} {'OK' if ok else 'FAIL ' + detail}")
        lines.append(f"- **{label}** `{model}` — {'authorized' if ok else 'DENIED: ' + detail}")

    lines.append("")
    ok, detail = check_json(llm.EXTRACT_MODEL)
    print(f"\nreasoning-OFF JSON: {'OK' if ok else 'FAIL ' + detail}")
    lines += [f"## Reasoning-OFF JSON validity", "",
              f"{'Parses cleanly.' if ok else 'FAILED: ' + detail}", ""]

    print("\ncontext ceiling probe...")
    ceiling_rows = find_ceiling(llm.ANSWER_MODEL)
    lines += ["## Measured context ceiling", "",
              "| requested tokens | accepted | provider-counted prompt tokens | latency (s) |",
              "|---|---|---|---|"]
    for actual, accepted, counted, secs in ceiling_rows:
        shown = "n/a" if secs is None else f"{secs}"
        lines.append(f"| {actual:,} | {'yes' if accepted else 'no'} | {counted:,} | {shown} |")
    passed = [r[0] for r in ceiling_rows if r[1]]
    ceiling = max(passed) if passed else 0
    hit_wall = any(not r[1] for r in ceiling_rows)
    lines += ["", f"**Largest accepted request: {ceiling:,} tokens.**", ""]
    if hit_wall:
        lines += [f"Set `HYDRAMEM_CONTEXT_CEILING={ceiling}` in `.env`. Requests above this",
                  "route to the overflow provider, and the split is disclosed by count.", ""]
    else:
        lines += ["No wall was found within the probed range. LongMemEval_S averages",
                  "~115k tokens per question, so **there is no overflow tail** and no",
                  "fallback provider is required for the full-context baseline.", ""]

    print("\nthroughput...")
    ok_n, secs, rpm = measure_rpm(llm.EXTRACT_MODEL)
    print(f"  {ok_n} calls in {secs}s -> ~{rpm} RPM")
    samples_file = pathlib.Path("docs/rpm-samples.json")
    samples = json.loads(samples_file.read_text()) if samples_file.exists() else []
    samples.append(rpm)
    samples_file.write_text(json.dumps(samples, indent=2))
    lines += ["## Observed throughput", "",
              f"Latest run: {ok_n} sequential uncached calls in {secs}s — **{rpm} req/min**.", "",
              f"Across {len(samples)} runs: **{min(samples)}–{max(samples)} req/min** "
              f"(median {sorted(samples)[len(samples)//2]}).", "",
              "NVIDIA documents the limit as varying with model, use case and current",
              "overall traffic, and the spread above confirms that. Treat ~40 RPM as a",
              "floor to plan against rather than a number to schedule against.", "",
              "## Spend", "", "**$0.** Free tier only; no paid plan enabled.", ""]

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote {REPORT}")


if __name__ == "__main__":
    main()
